# app.yaml
runtime: nodejs14
env: standard
# If you have one application, please use "default" for service
service: default
# VPC Network if you have one
#network:
#  name: default
handlers:
# Serve all static files with urls ending with a file extension
